
dataset: {
    dataset_name: 'nab',
    frequency: 'yearly',
    min_series_length: null,
    max_series_length: null,
    samples: 2,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 1,
    test_window: 0.001,
    retrain_scenarios: [1],
    'intervals': {
        'h': 1,
        'n_windows': 20,
        'method': 'conformal_distribution'
    },
    levels: [95, 99],
    store_in_sample_results: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    'MFLES',
    'TBATS'
]

model_params: {
    'ETS': {'season_length': 1, 'model': 'ZZZ'},
    'ARIMA': {'season_length': 1},
    'Theta': {'season_length': 1},
    'CES': {'season_length': 1},
    'MFLES': {'season_length': null, 'test_size': 10, 'metric': 'mse'},
    'TBATS': {'season_length': [1]},
}

target_transforms: null

features: {
    'static': null,
    'lags': null,
    'lag_transforms': null,
    'date': null,
    'xregs': null
}
