dataset: {
    dataset_name: 'nab',
    frequency: 'yearly',
    min_series_length: null,
    max_series_length: null,
    samples: null,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 96,
    test_window: 0.7,
    retrain_scenarios: [96],
    'intervals': {
        'h': 96,
        'n_windows': 5,
        'method': 'conformal_distribution'
    },
    levels: [99, 99.5],
    store_in_sample_results: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    'MFLES',
    'TBATS',
    'MSTL'
]

model_params: {
    'ETS': {'season_length': 1, 'model': 'ZZZ'},
    'ARIMA': {'season_length': 1},
    'Theta': {'season_length': 1},
    'CES': {'season_length': 1},
    'MFLES': {'season_length': null, 'test_size': 50, 'metric': 'mse'},
    'TBATS': {'season_length': [1]},
    'MSTL': {'season_length': [1]}
}

target_transforms: null

features: {
    'static': null,
    'lags': null,
    'lag_transforms': null,
    'date': null,
    'xregs': null
}
