
dataset: {
    dataset_name: 'nab',
    min_series_length: null,
    max_series_length: null,
    samples: 2,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 1,
    test_window: 0.002,
    retrain_scenarios: [1]
}

model_names: [
    'Zscore',
    'Pierce',
    'Chauvenet',
    'Grubbs',
    'Dixon',
    'Tukey',
    'Barbato',
    'Hampel'
]

model_params: {
    'Zscore': {'q': 3},
    'Pierce': {null},
    'Chauvenet': {null},
    'Grubbs': {'alpha': 0.01},
    'Dixon': {'alpha': 0.01, 'two_sided': True},
    'Tukey': {'extreme': True},
    'Barbato': {'extreme': True},
    'Hampel': {'bandwidth': 7, 'k': 6}
}