
dataset: {
    dataset_name: 'nab',
    frequency: 'yearly',
    min_series_length: null,
    max_series_length: null,
    samples: 2,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 1,
    test_window: 0.002,
    retrain_scenarios: [1],
    'intervals': {
        'h': 1,
        'n_windows': 20,
        'method': 'conformal_distribution'
    },
    levels: [99],
    store_in_sample_results: False
}

model_names: [
    'ETS'
]

model_params: {
    'ETS': {'model': 'ZZZ'},
}

target_transforms: null

features: {
    'static': null,
    'lags': null,
    'lag_transforms': null,
    'date': null,
    'xregs': null
}
