
dataset: {
    dataset_name: 'nab',
    frequency: 'yearly',
    min_series_length: null,
    max_series_length: null,
    samples: 2,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 28,
    test_window: 56,
    retrain_scenarios: [
        # 7, 
        # 14, 
        # 21,
        30, 
        # 60,
        # 90,
        # 120,
        # 150,
        # 180,
        # 364
    ],
    'intervals': {
        'h': 28,
        'n_windows': 4,
        'method': 'conformal_distribution'
    },
    levels: [50, 60, 70, 80, 90, 95, 99],
    store_in_sample_results: False
}

model_names: [
    'LinearRegression'
]
# model_params: null
model_params: {
    'LinearRegression': {'n_jobs': -1},
}
target_transforms: null
features: {
    'static': ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'],
    'lags': [1, 7, 14, 21, 28, 35, 42, 49, 56],
    'lag_transforms': {
                1: [RollingMean(7), RollingMean(14), RollingMean(30), ExpandingMean()],
                7: [RollingMean(7), RollingMean(14), RollingMean(30)],
                14: [RollingMean(7), RollingMean(14), RollingMean(30)],
                30: [RollingMean(7), RollingMean(14), RollingMean(30)]
            },
    'date': ['year', 'quarter', 'month', 'week', 'dayofweek', 'day', is_weekend],
    'xregs': ['event']
}