
dataset: {
    'dataset_name': 'nab',
    'ext': '.parquet'
}

fitting: {
    'retrain_scenarios': [96],
    'levels': [99, 99.5]
}

ensembling: {
    'model_names': [
        ['ETS', 'ARIMA'],
        ['ETS', 'Theta'],
        ['ARIMA', 'Theta'],
        ['ARIMA', 'TBATS'],
        ['ETS', 'ARIMA', 'Theta'],
        ['ETS', 'ARIMA', 'TBATS'],
        ['ETS', 'ARIMA', 'MSTL'],
        ['ARIMA', 'Theta', 'TBATS'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS'],
        ['ETS', 'ARIMA', 'Theta', 'MSTL'],
        ['ARIMA', 'Theta', 'TBATS', 'MSTL'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS', 'MSTL']
    ],
    'methods': ['mean'], 
    'name': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    'anomaly_threshold': 0.5
}
