
dataset: {
    'dataset_name': 'nab',
    'ext': '.parquet'
}

fitting: {
    'retrain_scenarios': [1],
    'levels': [95, 99]
}

ensembling: {
    'model_names': [
        ['ETS', 'ARIMA'],
        ['ETS', 'ARIMA', 'Theta'],
        ['ETS', 'ARIMA', 'TBATS'],
        ['ETS', 'ARIMA', 'MFLES'],
        ['ETS', 'ARIMA', 'MSTL'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS'],
        ['ETS', 'ARIMA', 'Theta', 'MFLES'],
        ['ETS', 'ARIMA', 'Theta', 'MSTL'],
        ['ETS', 'ARIMA', 'TBATS', 'MFLES'],
        ['ETS', 'ARIMA', 'TBATS', 'MSTL'],
        ['ETS', 'ARIMA', 'MFLES', 'MSTL'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS', 'MFLES'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS', 'MSTL'],
        ['ETS', 'ARIMA', 'Theta', 'MFLES', 'MSTL'],
        ['ETS', 'ARIMA', 'TBATS', 'MFLES', 'MSTL'],
        ['ETS', 'ARIMA', 'Theta', 'TBATS', 'MFLES', 'MSTL']
    ],
    'methods': ['mean'], 
    'name': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
    'anomaly_threshold': 0.5
}
