
dataset: {
    'dataset_name': 'nab',
    'ext': '.parquet'
}

fitting: {
    'retrain_scenarios': [1],
    levels: [95, 99],
    combine_only: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    'MFLES',
    'TBATS'
]

evaluation: {
    metrics: ['accuracy', 'recall', 'precision', 'f1', 'auc']
}
