
dataset: {
    'dataset_name': 'nab',
    'ext': '.parquet'
}

fitting: {
    'retrain_scenarios': [96],
    levels: [99, 99.5],
    combine_only: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    # 'MFLES',
    'TBATS', 
    'MSTL',
    'EnsembleMean1',
    'EnsembleMean2',
    'EnsembleMean3',
    'EnsembleMean4',
    'EnsembleMean5',
    'EnsembleMean6',
    'EnsembleMean7',
    'EnsembleMean8',
    'EnsembleMean9',
    'EnsembleMean10',
    'EnsembleMean11',
    'EnsembleMean12'
]

evaluation: {
    metrics: ['accuracy', 'recall', 'precision', 'f1', 'auc']
}
