
dataset: {
    dataset_name: 'nab',
    frequency: 'yearly',
    min_series_length: null,
    max_series_length: null,
    samples: null,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    'retrain_scenarios': [96],
    levels: [99, 99.5],
    combine_only: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    # 'MFLES',
    'TBATS',
    'MSTL',
    'EnsembleMean1',
    'EnsembleMean2',
    'EnsembleMean3',
    'EnsembleMean4',
    'EnsembleMean5',
    'EnsembleMean6',
    'EnsembleMean7',
    'EnsembleMean8',
    'EnsembleMean9',
    'EnsembleMean10',
    'EnsembleMean11',
    'EnsembleMean12'
]

evaluation: {
    metrics: ['bias', 'mae', 'mse', 'rmse', 'mase', 'msse', 'rmsse', 'mql', 'smql'], #  'mql', 'smql', 'scrps'
    evaluation_frequency: 'yearly', # frequency for mase, msse, rmsse
}
