
dataset: {
    'dataset_name': 'm5',
    'frequency': 'daily',
    'min_series_length': 730,
    'samples': null,
    'ext': '.parquet',
    'seed': 1992
}

fitting: {
    'retrain_scenarios': [
        7, 
        14, 
        21,
        30, 
        60,
        90,
        120,
        150,
        180,
        364
    ],
    levels: [50, 60, 70, 80, 90, 95, 99],
    combine_only: False
}

model_names: [
    # 'LinearRegression', 
    # 'RandomForestRegressor', 
    # 'XGBRegressor', 
    # 'LGBMRegressor', 
    # 'CatBoostRegressor',
    # 'MLP',
    # 'LSTM',
    # 'TCN',
    # 'NBEATSx',
    # 'NHITS',
    'EnsembleMean2A',
    'EnsembleMean2T',
    'EnsembleMean3A',
    'EnsembleMean3T',
    'EnsembleMean4A',
    'EnsembleMean4T',
    'EnsembleMean5A',
    'EnsembleMean5T'
]

evaluation: {
    metrics: ['bias', 'mae', 'mse', 'rmse', 'mase', 'msse', 'rmsse', 'mql', 'smql', 'scrps'], # 'ql', 'cal', 'cov', 'sql'
    evaluation_frequency: 'daily', # frequency for mase, msse, rmsse
    evaluation_sample_type: 'overlap' # nooverlap
}
