
dataset: {
    'dataset_name': 'nab',
    'ext': '.parquet'
}

fitting: {
    'retrain_scenarios': [1],
    levels: [95, 99],
    combine_only: False
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    'MFLES',
    'TBATS', 
    'EnsembleMean1',
    'EnsembleMean2',
    'EnsembleMean3',
    'EnsembleMean4',
    'EnsembleMean5',
    'EnsembleMean6',
    'EnsembleMean7',
    'EnsembleMean8'
]

evaluation: {
    metrics: ['accuracy', 'recall', 'precision', 'f1', 'auc']
}
