
dataset: {
    'dataset_names': ['nab'],
    'ext': '.parquet'
}

model_names: [
    'ETS',
    'ARIMA',
    'Theta',
    # 'CES',
    # 'MFLES',
    'TBATS',
    'MSTL',
    'EnsembleMean1',
    'EnsembleMean2',
    'EnsembleMean3',
    'EnsembleMean4',
    'EnsembleMean5',
    'EnsembleMean6',
    'EnsembleMean7',
    'EnsembleMean8',
    'EnsembleMean9',
    'EnsembleMean10',
    'EnsembleMean11',
    'EnsembleMean12'
]
